# Generated by Django 5.0.4 on 2024-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadapp', '0006_alter_follow_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
    ]
