# Generated by Django 5.0.4 on 2024-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadapp', '0007_post_likescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentsCount',
            field=models.IntegerField(default=0),
        ),
    ]
