# Generated by Django 5.0.4 on 2024-05-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadapp', '0010_community_img_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='img',
            field=models.FileField(default='media/defaultCom.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.FileField(default='media/default.jpg', upload_to='media'),
        ),
    ]
