# Generated by Django 5.0.4 on 2024-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadapp', '0012_alter_community_img_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='img',
            field=models.FileField(default='/media/defaultCom', upload_to='media'),
        ),
    ]
