# Generated by Django 5.0.4 on 2024-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadapp', '0013_alter_community_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='img',
            field=models.FileField(default='defaultCom.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.FileField(default='default.jpg', upload_to='media'),
        ),
    ]
