# Generated by Django 5.0.4 on 2024-05-10 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadapp', '0014_alter_community_img_alter_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='breadapp.profile'),
        ),
    ]
