# Generated by Django 5.0.4 on 2024-05-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadapp', '0016_alter_notification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
